project_id = "mkuaoxegdoqizxwbrtlm"

[functions.external-achievements]
verify_jwt = false

[functions.contact-notify]
verify_jwt = false

[functions.og-image]
verify_jwt = false

[functions.github-webhook]
verify_jwt = false

[functions.skill-snapshot]
verify_jwt = false